### PR TITLE
feat: support remove redundant close brackets

### LINKED ISSUE #103: Support remove redundant close brackets?
image

related to https://github.com/josdejong/jsonrepair/issues/88#issuecomment-1434302464

### PR DESCRIPTION
**Pull request by vagusX**
close #103

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for your PR @vagusX ! Very nice to improve on wrong/redundant closing brackets. 

I think your current implementation is a bit dangerous though: it basically just ignores any "garbage" characters at the end without checking what it throws away. So, for example the input `{"a":2}{"a":3}{"a":4}` will happily output `{"a":2}`, throwing away two objects. 

I think a safer solution would be to write a loop skipping over any closing brackets `}` and `]` (with possible white spacing in between). Does that make sense?

**Comment by vagusX** [comment]
> Thanks for your PR @vagusX ! Very nice to improve on wrong/redundant closing brackets.
> 
> I think your current implementation is a bit dangerous though: it basically just ignores any "garbage" characters at the end without checking what it throws away. So, for example the input `{"a":2}{"a":3}{"a":4}` will happily output `{"a":2}`, throwing away two objects.
> 
> I think a safer solution would be to write a loop skipping over any closing brackets `}` and `]` (with possible white spacing in between). Does that make sense?

Thank you for your suggestion, but I may not have fully understood what you meaning about `write a loop skipping over any closing brackets } and ] (with possible white spacing in between`.

Should I check if all remaining characters which besides the output, are closed brackets such as `{` and `[`?

**Comment by josdejong** [comment]
@vagusX if you want I can implement this idea?

**Comment by josdejong** [comment]
Sorry I couldn't wait, and I've implemented and published a fix now based on your PR: f81ffad5f30fc7e3cec8f1481f8b189c6a4eb49f. Thanks again for bringing this up and working on a solution.

**Comment by vagusX** [comment]
> Sorry I couldn't wait, and I've implemented and published a fix now based on your PR: [f81ffad](https://github.com/josdejong/jsonrepair/commit/f81ffad5f30fc7e3cec8f1481f8b189c6a4eb49f). Thanks again for bringing this up and working on a solution.

I apologize for not keeping up with this PR in a timely manner, but I'm glad to see that this feature has finally been shipped out.

**Pull request closed without merging**
